version: '1.0.{build}'
os: Visual Studio 2019
configuration: Release
platform:
    - x64
branches:
  only:
    - master

environment:
    MyProjectDir: C:\projects\MoveExeWindow\
    OpenCvDir: C:\projects\opencv\
    OpenCvUrl: https://github.com/GengGode/opencv450Release/releases/download/v1.0/Release.zip
    ProjectName: 进程窗口位置调整
    ProJectExeName: 进程窗口位置调整
skip_tags: true
  
install:
    - ps: $env:TIME_STRING=(get-date -UFormat "%Y%m%d%a").ToString()
before_build: 
    - dir  %MyProjectDir%
build_script:
    - MSBuild

after_build:
    # copy include and source code files
    #- ls
    - mkdir %MyProjectDir%x64\build\
    - ps: cp -r $env:MyProjectDir\cvAutoTrack\x64\Release\*.dll $env:MyProjectDir\x64\build\
    - ps: cp -r $env:MyProjectDir\cvAutoTrack\x64\Release\*.lib $env:MyProjectDir\x64\build\
    - ps: cp -r $env:MyProjectDir\cvAutoTrack\include\*.h $env:MyProjectDir\x64\build\
    
    - echo %APPVEYOR_BUILD_VERSION% >version.tag
    - 7z a 进程窗口位置调整.7z %MyProjectDir%x64\build\*

    - appveyor PushArtifact version.tag
    - appveyor PushArtifact 进程窗口位置调整.7z
    
#artifacts:
    #- path: build/Release
    #artifacts path name must be appveyor API
  
deploy:
    - provider: GitHub
      description: '$(APPVEYOR_PROJECT_SLUG): 进程窗口位置调整  $(APPVEYOR_BUILD_VERSION)' 
      auth_token:
         secure: G/Fzf0bGIhqqt+XvsC5AXrZVNs3atGU7XCzJxqiUZEwOxoZrjxk87ENI/OitnXCo
      draft: false
      tag: $(APPVEYOR_BUILD_VERSION)
      force_update: true
      on:  
        APPVEYOR_REPO_TAG: false

notifications:
  - provider: Email
    to:
      - ysx20201030@163.com
    subject: '{{status}}: {{projectName}} {{buildVersion}}'                  # optional
    message: "<h1>Build</h1>
                <h2>{{projectName}} {{status}}</h2>
                    <p>{{buildVersion}}: {{buildUrl}}</p>
               <H1>Commit</h1> 
                <h3>#{{commitId}} by {{commitAuthor}} on {{commitDate}}</h3><h2> {{commitMessage}}</h2>"    # optional
    on_build_success: true
    on_build_failure: false
    on_build_status_changed: false
